name: fedimintd_mobile
description: "A flutter project for running fedimintd"
publish_to: 'none'
version: 0.1.0+10090

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  http: ^1.2.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  flutter_foreground_task: ^8.13.0
  permission_handler: ^11.3.1
  mobile_scanner: ^3.5.0
  share_plus: ^10.0.0
  web_socket_channel: ^3.0.0
  json_rpc_2: ^3.0.3
  file_picker: ^8.0.0+1
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/fedimint.png
    - assets/images/fedimint-icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/fedimint.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/fedimint.png"